# Generated by Django 4.2.7 on 2024-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkdein',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(default='General', max_length=130),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
