# Generated by Django 4.2.7 on 2024-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_rename_linkdein_profile_linkedin_profile_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-datetime']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='General', max_length=130),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
