# Generated by Django 4.2.7 on 2024-01-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0004_alter_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(choices=[('1', 'general'), ('2', 'python'), ('3', 'django'), ('4', 'web designing')], default='general', max_length=20),
        ),
    ]
