# Generated by Django 4.2.7 on 2024-01-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0005_alter_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.TextField(),
        ),
    ]
