# Generated by Django 3.2.1 on 2024-01-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0005_alter_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.TextField(),
        ),
    ]
